#!/usr/bin/env python3
"""Extract STIX's unencoded MATH parentheses/brackets into a supplemental font.

Requires fonttools and lv_font_conv 1.5.3. Existing math fonts are untouched.
"""
import argparse, re, subprocess, tempfile
from pathlib import Path
from fontTools.ttLib import TTFont

ROOT=Path(__file__).resolve().parents[1]

def main():
    ap=argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--converter',default='lv_font_conv')
    args=ap.parse_args()
    font=TTFont(ROOT/'assets/fonts/STIXTwoMath-Regular.ttf')
    variants=font['MATH'].table.MathVariants
    names=[]
    for cp in (40,41,91,93):
        construction=variants.VertGlyphConstruction[variants.VertGlyphCoverage.glyphs.index(font.getBestCmap()[cp])]
        assert len(construction.MathGlyphVariantRecord)==13
        assert [p.PartFlags for p in construction.GlyphAssembly.PartRecords]==[0,1,0]
        names.extend(v.VariantGlyph for v in construction.MathGlyphVariantRecord)
        # OpenType lists assembly parts bottom to top; our plan is top/middle/bottom.
        names.extend(p.glyph for p in reversed(construction.GlyphAssembly.PartRecords))
    assert len(names)==64
    assert font['head'].unitsPerEm==1000
    bracket=variants.VertGlyphConstruction[variants.VertGlyphCoverage.glyphs.index(font.getBestCmap()[91])]
    parts=bracket.GlyphAssembly.PartRecords
    max_overlap=min(parts[0].EndConnectorLength,parts[1].StartConnectorLength,
                    parts[1].EndConnectorLength,parts[2].StartConnectorLength)
    assert 0<variants.MinConnectorOverlap<=max_overlap
    for table in font['cmap'].tables:
        if table.isUnicode():
            table.cmap.update({0xe000+i:name for i,name in enumerate(names)})
    all_metrics=[]
    with tempfile.TemporaryDirectory() as temp:
        mapped=Path(temp)/'stix-parentheses.ttf';font.save(mapped)
        for size in (18,12,8):
            dest=ROOT/f'src/fonts/stix_parens_{size}.c'
            subprocess.run([args.converter,'--font',str(mapped),'--size',str(size),'--bpp','4',
                '--format','lvgl','--range','0xe000-0xe03f','--no-compress','--no-kerning','-o',str(dest)],check=True)
            text=dest.read_text().replace('#include "lvgl/lvgl.h"','#include "lvgl.h"')
            # Remove temporary paths from generated comments for reproducibility.
            text=re.sub(r' \* Opts:.*\n',' * Generated by scripts/generate-stix-parentheses.py\n',text)
            text='/* STIX Two Math; Copyright 2001-2021 The STIX Fonts Project Authors.\n * Source: assets/fonts/STIXTwoMath-Regular.ttf\n * License: assets/fonts/LICENSES/STIXTwoMath-OFL-1.1.txt (OFL-1.1).\n */\n'+text
            dest.write_text(text.rstrip()+"\n")
            glyphs=re.findall(r'\.adv_w = (\d+), \.box_w = (\d+), \.box_h = (\d+), \.ofs_x = (-?\d+), \.ofs_y = (-?\d+)',text)
            assert len(glyphs)==65
            all_metrics.append([(int(w),int(h),int(x),int(y),(int(adv)+8)//16) for adv,w,h,x,y in glyphs[1:]])
    header='''// Generated by scripts/generate-stix-parentheses.py; STIX OFL-1.1.
#pragma once
#include <cstdint>
namespace vpam {
struct StixParenInk { int16_t width, height, xOffset, yOffset, advance; };
'''
    for size,metrics in zip((18,12,8),all_metrics):
        header+=f'inline constexpr StixParenInk kStixParens{size}[] = {{\n'
        for name,m in zip(names,metrics):header+='    {'+', '.join(map(str,m))+'}, // '+name+'\n'
        header+='};\n'
    header+=f'inline constexpr int16_t kStixBracketMinOverlapDu = {variants.MinConnectorOverlap};\n'
    header+=f'inline constexpr int16_t kStixBracketMaxOverlapDu = {max_overlap};\n'
    header+='} // namespace vpam\n'
    (ROOT/'src/math/font/stix_parenthesis_ink.h').write_text(header)
if __name__=='__main__':main()
