#!/usr/bin/env python3
"""Generate immutable Toolbox rows and the review inventory from one source."""
import argparse, json
from pathlib import Path
root=Path(__file__).resolve().parents[1]
p=argparse.ArgumentParser();p.add_argument('--check',action='store_true');p.add_argument('--source',type=Path,default=root/'src/math/toolbox-catalog.json');a=p.parse_args()
rows=json.loads(a.source.read_text(encoding='utf-8'))
seen=set()
for e in rows:
    identity=e['id'],e['variant']
    assert identity not in seen, f'duplicate identity {identity}'
    seen.add(identity)
    for key in ('en','es','helpEn','helpEs','aliases','expected'):
        assert e[key] and len(e[key].encode('utf-8'))<192, (identity,key)
        assert '?' not in e[key] and '\ufffd' not in e[key], (identity,key,'damaged encoding')
    assert 0<e['capabilities']<=15 and (e['category']==0 or 10<=e['category']<=21)
    assert isinstance(e['keyboardShortcut'],bool)
    assert isinstance(e.get('caseSensitiveAliases',False),bool)
    if e['recipe']=='Symbol':
        cp=e['argument'];assert (0x391<=cp<=0x3a9 and cp!=0x3a2) or 0x3b1<=cp<=0x3c9 or cp in (0x3d1,0x3d5,0x3d6,0x3f5)
    if e['recipe']=='Variable':assert 65<=e['argument']<=90 or 97<=e['argument']<=122
    if e['recipe']=='Infinity':assert e['argument'] in ('BarePositiveInfinity','PositiveInfinity','NegativeInfinity','BothInfinities')
    if e['options']>=1000:assert e['variant'] in (0,1)
    assert len(e['previewArgs'])<=4 and all('a'<=c<='z' for c in e['previewArgs'])
quote=lambda s:json.dumps(s,ensure_ascii=False)
inc='// Generated by scripts/generate-toolbox-catalog.py; edit toolbox-catalog.json.\n'
doc='# Toolbox catalogue (generated)\n\nPreviews use the same AST structure with display-only parameter letters. Insertions contain empty slots. C=Calculation, E=Equations, D=Calculus, G=Grapher. Keyboard entries remain resolvable for existing favorites but are absent from browsing and search. Arguments are in cursor traversal order. No selection capture.\n\n| ID:variant | EN / ES | Recipe | Apps | Discovery | Preview parameters | Fixture arguments | Expected | Help / limits |\n|---|---|---|---|---|---|---|---|---|\n'
for e in rows:
    tag={'Call':'InputCall','Function':'vpam::FuncKind','Constant':'vpam::ConstKind','Infinity':'vpam::SpecialValueKind'}.get(e['recipe'])
    argument=f'uint8_t({tag}::{e["argument"]})' if tag else str(e['argument'])
    strings=', '.join(quote(e[k]) for k in ('en','es','helpEn','helpEs','aliases'))
    inc+=f'{{{{{e["id"]},{e["variant"]}}}, {e["category"]}, Recipe::{e["recipe"]}, {argument}, {e["capabilities"]}, {strings}, {e["options"]}, {str(e.get("caseSensitiveAliases",False)).lower()}, {str(e["keyboardShortcut"]).lower()}, {quote(e["previewArgs"])}}},\n'
    caps=''.join(c for bit,c in [(1,'C'),(2,'E'),(4,'D'),(8,'G')] if e['capabilities']&bit)
    doc+=f'| {e["id"]}:{e["variant"]} | {e["en"]} / {e["es"]} | {e["recipe"]}({e["argument"]}) | {caps} | {"Keyboard / existing favorites" if e["keyboardShortcut"] else "Toolbox"} | {e["previewArgs"]} | {", ".join(e["fixture"])} | {e["expected"]} | {e["helpEn"]} |\n'
for path,content in [('src/math/ToolboxEntries.inc',inc),('docs/TOOLBOX_01_CATALOG.md',doc)]:
    target=root/path
    if a.check: assert target.read_text(encoding='utf-8')==content, path+' is stale'
    else: target.write_text(content,encoding='utf-8')
print(f'{len(rows)} validated identities; generated files '+('current' if a.check else 'written'))
